make:
	# g++ aes_ecb_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ecb_enc.o
	# g++ aes_ecb_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ecb_dec.o
	#
	# g++ aes_cbc_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_cbc_enc.o
	# g++ aes_cbc_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_cbc_dec.o
	#
	# g++ aes_ctr_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ctr_enc.o
	# g++ aes_ctr_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ctr_dec.o
	#
	# g++ sm4_ecb_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_ecb_enc.o
	# g++ sm4_ecb_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_ecb_dec.o

	# g++ sm4_cbc_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_cbc_enc.o
	# g++ sm4_cbc_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_cbc_dec.o

	# g++ sm4_ctr_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_ctr_enc.o
	# g++ sm4_ctr_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm4_ctr_dec.o
	#
	# g++ aes_ctr_enc.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ctr_enc.o
	# g++ aes_ctr_dec.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o aes_ctr_dec.o

	# Hash algorithms: SM3 and SHA256
	# g++ sm3.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm3
	# g++ sha256.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sha256
	#
	# # RSA: Key generation, signature generation, signature verification
	# g++ rsa_keygen.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o rsa_keygen
	# g++ rsa_sign.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o rsa_sign
	# g++ rsa_verify.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o rsa_verify
	#
	# # ECDSA: key generation, signature generation, signature verification
	# g++ ecdsa_keygen.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o ecdsa_keygen
	# g++ ecdsa_sign.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o ecdsa_sign
	# g++ ecdsa_verify.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o ecdsa_verify
	#
	# # SM2: key generation, signature generation, signature verification
	# g++ sm2_keygen.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm2_keygen
	# g++ sm2_sign.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm2_sign
	# g++ sm2_verify.cpp -std=c++11 -I/usr/local/include/botan-2 -lbotan-2 -ldl -lrt -o sm2_verify


clean:
	rm -f *.o
	rm -f *_iv
	rm -f *.bin
